### ISSUE TITLE
GetAtt includes Arn in function name

### ISSUE THREAD

**Issue by jrowen** [nathanagez/aws-cdk-state-machine-asl#1]
Great tool, thanks for putting it together.  I'm running into an issue with Lambda function names.  In my template, the definition often includes something like the following

       {
        "Fn::GetAtt": [
         "LambdaFunc3EFEE6DE",
         "Arn"
        ]
       },

The code parses this as `LambdaFunc3EFEE6DEArn`, which is not recognized the Lambda server running locally.  In particular, the `Arn` suffix is causing the issue, as `sam local` will make the function available under `LambdaFunc3EFEE6DE`.

Is this expected behavior, and should I be structing my cdk files or running the local Lambda server differently to get around this issue?

**Comment by elthrasher** [comment]
@jrowen I ran into the same issue. Since my app was for demo purposes only, I used [patch-package](https://www.npmjs.com/package/patch-package) to do [this](https://github.com/aws-community-projects/cdkday-localvcloud/blob/main/patches/cdk-asl-extractor%2B1.0.1.patch) which enabled me to use the extracted ASL with SAM. @nathanagez I'll be happy to open a PR if you're interested in that solution.

**Comment by nathanagez** [comment]
Thanks for reporting this issue @jrowen !
@elthrasher yes please, feel free to open a PR 🚀

**Comment by elthrasher** [comment]
@nathanagez I thought about getting elaborate, but wound up making it a one-liner :D
